title: hrysd.org

description: >
  hrysd の公式サイト

keywords:
  - hrysd
  - 豆乳

url: 'https://hrysd.org'

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

sass:
  sass_dir: stylesheets
  style: compressed
